# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EDA.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EDA(object):
    def setupUi(self, EDA):
        EDA.setObjectName("EDA")
        EDA.resize(1680, 964)
        self.verticalLayout = QtWidgets.QVBoxLayout(EDA)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scroll_analisis = QtWidgets.QScrollArea(EDA)
        self.scroll_analisis.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_analisis.sizePolicy().hasHeightForWidth())
        self.scroll_analisis.setSizePolicy(sizePolicy)
        self.scroll_analisis.setMaximumSize(QtCore.QSize(10000, 10000))
        self.scroll_analisis.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll_analisis.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scroll_analisis.setWidgetResizable(True)
        self.scroll_analisis.setAlignment(QtCore.Qt.AlignCenter)
        self.scroll_analisis.setObjectName("scroll_analisis")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(8, 0, 1662, 962))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graficas = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graficas.sizePolicy().hasHeightForWidth())
        self.graficas.setSizePolicy(sizePolicy)
        self.graficas.setObjectName("graficas")
        self.graph_layout = QtWidgets.QGridLayout(self.graficas)
        self.graph_layout.setContentsMargins(0, 0, 0, 0)
        self.graph_layout.setObjectName("graph_layout")
        self.features_box = QtWidgets.QComboBox(self.graficas)
        self.features_box.setObjectName("features_box")
        self.graph_layout.addWidget(self.features_box, 0, 1, 1, 1)
        self.feature_label = QtWidgets.QLabel(self.graficas)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.feature_label.setFont(font)
        self.feature_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.feature_label.setObjectName("feature_label")
        self.graph_layout.addWidget(self.feature_label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.graph_layout.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.graficas, 14, 0, 1, 2)
        self.object_plot = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.object_plot.setObjectName("object_plot")
        self.object_plot_grid = QtWidgets.QGridLayout(self.object_plot)
        self.object_plot_grid.setContentsMargins(9, 9, 9, 9)
        self.object_plot_grid.setObjectName("object_plot_grid")
        self.label = QtWidgets.QLabel(self.object_plot)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.object_plot_grid.addWidget(self.label, 0, 0, 1, 1)
        self.object_feature_box = QtWidgets.QComboBox(self.object_plot)
        self.object_feature_box.setObjectName("object_feature_box")
        self.object_plot_grid.addWidget(self.object_feature_box, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.object_plot_grid.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.object_plot, 15, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 11, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.missed_table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.missed_table.sizePolicy().hasHeightForWidth())
        self.missed_table.setSizePolicy(sizePolicy)
        self.missed_table.setObjectName("missed_table")
        self.missed_table.setColumnCount(0)
        self.missed_table.setRowCount(0)
        self.gridLayout_3.addWidget(self.missed_table, 12, 0, 1, 1)
        self.estruct_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estruct_label.sizePolicy().hasHeightForWidth())
        self.estruct_label.setSizePolicy(sizePolicy)
        self.estruct_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.estruct_label.setFont(font)
        self.estruct_label.setObjectName("estruct_label")
        self.gridLayout_3.addWidget(self.estruct_label, 7, 0, 1, 1)
        self.preview_table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.preview_table.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_table.sizePolicy().hasHeightForWidth())
        self.preview_table.setSizePolicy(sizePolicy)
        self.preview_table.setMinimumSize(QtCore.QSize(256, 0))
        self.preview_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.preview_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.preview_table.setAutoScroll(False)
        self.preview_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.preview_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.preview_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.preview_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.preview_table.setObjectName("preview_table")
        self.preview_table.setColumnCount(0)
        self.preview_table.setRowCount(0)
        self.gridLayout_3.addWidget(self.preview_table, 4, 0, 1, 1)
        self.estruct_table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estruct_table.sizePolicy().hasHeightForWidth())
        self.estruct_table.setSizePolicy(sizePolicy)
        self.estruct_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.estruct_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.estruct_table.setTabKeyNavigation(False)
        self.estruct_table.setProperty("showDropIndicator", False)
        self.estruct_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.estruct_table.setObjectName("estruct_table")
        self.estruct_table.setColumnCount(0)
        self.estruct_table.setRowCount(0)
        self.estruct_table.verticalHeader().setHighlightSections(False)
        self.gridLayout_3.addWidget(self.estruct_table, 9, 0, 1, 1)
        self.preview_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_label.sizePolicy().hasHeightForWidth())
        self.preview_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.preview_label.setFont(font)
        self.preview_label.setObjectName("preview_label")
        self.gridLayout_3.addWidget(self.preview_label, 2, 0, 1, 1)
        self.faltantes_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.faltantes_label.sizePolicy().hasHeightForWidth())
        self.faltantes_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.faltantes_label.setFont(font)
        self.faltantes_label.setObjectName("faltantes_label")
        self.gridLayout_3.addWidget(self.faltantes_label, 10, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 13, 0, 1, 1)
        self.scroll_analisis.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scroll_analisis)

        self.retranslateUi(EDA)
        QtCore.QMetaObject.connectSlotsByName(EDA)

    def retranslateUi(self, EDA):
        _translate = QtCore.QCoreApplication.translate
        EDA.setWindowTitle(_translate("EDA", "Form"))
        self.feature_label.setText(_translate("EDA", "Selección de Característica"))
        self.label.setText(_translate("EDA", "Selección de Característica"))
        self.label_6.setText(_translate("EDA", "Conteo de datos nulos en tu conjunto de datos, por característica."))
        self.label_4.setText(_translate("EDA", "El conjunto de datos que importaste."))
        self.label_5.setText(_translate("EDA", "Tipos de datos que conforman tu conjunto de datos."))
        self.label_2.setText(_translate("EDA", "EDA - Análisis Exploratorio de Datos"))
        self.missed_table.setSortingEnabled(True)
        self.estruct_label.setText(_translate("EDA", "Tipos de Datos"))
        self.preview_label.setText(_translate("EDA", "Conjunto de Datos"))
        self.faltantes_label.setText(_translate("EDA", "Conteo de Datos Nulos"))
        self.label_3.setText(_translate("EDA", "En esta sección, podrás revisar la descripción de los datos para comprender lo que significa cada una de las características. \n"
"• Paso 1: Descripción de la estructura de los datos.\n"
"• Paso 2: Identificación de datos faltantes (o valores nulos). \n"
"• Paso 3: Detección de valores atípicos.\n"
"• Paso 4: Identificación de relaciones entre pares variables."))
        self.label_7.setText(_translate("EDA", "Selecciona la característica deseada para observar su comportamiento gráfico."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EDA = QtWidgets.QWidget()
    ui = Ui_EDA()
    ui.setupUi(EDA)
    EDA.show()
    sys.exit(app.exec_())
